### ISSUE TITLE
plans to allow save/recall of settings?

### ISSUE THREAD

**Issue by chappydboz** [Timendus/soundboard#36]
love it so far, just wondering. i do see it in the ideas post

**Comment by Timendus** [comment]
Hey there @chappydboz, thanks for asking, you're the third person actually reaching out with that same question 😄

I wasn't planning on doing much work on the soundboard any time soon, but if you all think this would be a nice feature, I guess it may be worth it! What do you think would be the best way to save and recall the settings (and sound files)? Storing them in the browser, or being able to download a settings file, or..?

To gauge interest, I've opened a "motivational fund" on Ko-fi. Don't feel pressured if you don't like paying for software, but feel free to donate if you do want to support this Open Source project.

https://ko-fi.com/timendus/commissions

**Comment by chappydboz** [comment]
browser storage would be great to start with, but settings file import/export seems like the best long-term feature for power users - ie. people integrating with livestream or podcasting setups.

thanks!

**Comment by Timendus** [comment]
It took a while... but I've added support for this!

The soundboard will now hold its audio files and settings, even if you close the website / app. There are also save and load buttons in the settings panel, so you can export your boards to disk and share them with other people.

Thanks a bunch to the people who contributed to the "motivational fund" and those who helped brainstorm solutions! ❤️

**Comment by chappydboz** [comment]
awesome! thanks for a great feature!
